### ISSUE TITLE
crashes on run

### ISSUE THREAD

**Issue by blade10101** [RNDpacman/blockchain_dns_system#1]
~/blockchain_dns_system$ sudo docker-compose up -d
Building unbound
[+] Building 0.8s (7/7) FINISHED                                                                            docker:default
 => [internal] load .dockerignore                                                                                     0.0s
 => => transferring context: 2B                                                                                       0.0s
 => [internal] load build definition from Dockerfile                                                                  0.0s
 => => transferring dockerfile: 545B                                                                                  0.0s
 => [internal] load metadata for docker.io/mvance/unbound:latest                                                      0.7s

 => CANCELED [1/3] FROM docker.io/mvance/unbound@sha256:c7981ac1677e18c7629de0cc67131a48c401f4448666d72bb963e47cf459  0.0s
 => => resolve docker.io/mvance/unbound@sha256:c7981ac1677e18c7629de0cc67131a48c401f4448666d72bb963e47cf4594294       0.0s
 => [internal] load build context                                                                                     0.0s
 => => transferring context: 186B                                                                                     0.0s
 => CACHED [2/3] WORKDIR /opt/unbound/etc/unbound                                                                     0.0s
 => ERROR [3/3] COPY ./emc-stub-records.conf . &&      ./insecure-dns.conf . &&      ./unbound.conf . &&      ./ygg-  0.0s
------
 > [3/3] COPY ./emc-stub-records.conf . &&      ./insecure-dns.conf . &&      ./unbound.conf . &&      ./ygg-forward-records.conf .:
------
Dockerfile:13
--------------------
  12 |     
  13 | >>> COPY ./emc-stub-records.conf . && \
  14 | >>>      ./insecure-dns.conf . && \
  15 | >>>      ./unbound.conf . && \
  16 | >>>      ./ygg-forward-records.conf .
  17 |     
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 06edd6b2-b6e7-4f27-a738-bccbc223a18f::8gf21ai0f8dddwce460jmeuln: "/&&": not found
ERROR: Service 'unbound' failed to build : Build failed

**Comment by RNDpacman** [comment]
I fixed it. Try again.
